ems/ems/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('myapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ems/myapp/urls.py
from django.urls import path

from myapp import views

urlpatterns = [
    
    # path('employees/all/', views.employees_list_view, name='employees-list'),

    path('', views.EmployeeListView.as_view(), name='employee-list'),

    path('employees/add/', views.EmployeeCreateView.as_view(), name='employee-add'),

    path('employees/<int:pk>/', views.EmployeeDetailView.as_view(), name='employee-detail'),

    path('employees/<int:pk>/remove/', views.EmployeeDeleteView.as_view(), name='employee-delete'),

    path('employees/<int:pk>/change/', views.EmployeeUpdateView.as_view(), name='employee-update'),

]

ems/myapp/models.py
from django.db import models

# Create your models here.


STATUS_CHOICE = {
    ('Active', 'Active'),
    ('Inactive', 'Inactive'),
}

GENDER_CHOICE = {
    ('Male', 'Male'),
    ('Female', 'Female'),
} 




class EmployeeDetails(models.Model):

    emp_id = models.CharField(max_length=20, unique=True)

    first_name = models.CharField(max_length=200)

    last_name = models.CharField(max_length=200)

    phone = models.CharField(max_length=20)

    email = models.CharField(max_length=200)

    address = models.CharField(max_length=300, blank=True, null=True)

    gender = models.CharField(max_length=50, choices=GENDER_CHOICE, default='Male')

    dob = models.DateField(blank=True,null=True)

    date_hired = models.DateField()

    status = models.CharField(max_length=100, choices=STATUS_CHOICE, default='Active')

    department = models.CharField(max_length=200)

    position = models.CharField(max_length=200)

    salary = models.DecimalField(max_digits=10, decimal_places=2)

    image = models.ImageField(upload_to="images", default="images/default.jpg", blank=True, null=True)

    date_added = models.DateTimeField(auto_now_add=True)

    date_updated = models.DateTimeField(auto_now=True)

    
    def __str__(self):

        return (self.first_name + ' ' + self.last_name)

ems/myapp/forms.py
from django import forms

from myapp.models import EmployeeDetails




class EmployeeDetailsForm(forms.ModelForm):

    
    class Meta:
            
        model = EmployeeDetails
        fields = "__all__"

        widgets = {
            'emp_id': forms.TextInput(attrs={'class':'form-control mb-3'}),
            'first_name': forms.TextInput(attrs={'class':'form-control mb-3'}),
            'last_name':  forms.TextInput(attrs={'class':'form-control mb-3'}),
            'phone': forms.TextInput(attrs={'class':'form-control mb-3', 'type': 'number', 'min':'0', 'placeholder': '10-digit mobile number'}),
            'email': forms.TextInput(attrs={'class':'form-control mb-3', 'placeholder': 'example@example.com'}),
            'address': forms.Textarea(attrs={'class':'form-control mb-3', 'rows':4}),
            'gender': forms.RadioSelect(attrs={'class':'form-check', 'type': 'radio'}),
            'dob': forms.DateInput(attrs={'class':'form-control mb-3', 'type': 'date'}),
            'date_hired': forms.DateInput(attrs={'class':'form-control mb-3', 'type': 'date'}),
            'status': forms.Select(attrs={'class':'form-select mb-3'}),
            'department': forms.TextInput(attrs={'class':'form-control mb-3'}),
            'position': forms.TextInput(attrs={'class':'form-control mb-3'}),
            'salary': forms.NumberInput(attrs={'class':'form-control mb-3', 'min': '0'}),
            'image': forms.FileInput(attrs={'class':'form-control mb-3'})
        }

        

ems/myapp/views.py
from django.shortcuts import render, redirect

from myapp.models import EmployeeDetails

from django.views.generic import View

from myapp.forms import EmployeeDetailsForm

# Create your views here.

# def employees_list_view(request, *args, **kwargs):

#     data = EmployeeDetails.objects.all()
    
#     return render(request, 'myapp/employee_list.html', {'data': data})


class EmployeeListView(View):
    
    def get(self, request, *args, **kwargs):

        data = EmployeeDetails.objects.all()

        return render(request, 'myapp/employee_list.html', {'data': data})
    


class EmployeeCreateView(View):

    def get(self, request, *args, **kwargs):

        form = EmployeeDetailsForm()

        return render(request, 'myapp/employee_add.html', {'form': form})
    
    
    def post(self, request, *args, **kwargs):
        
        # print(request.POST)

        form = EmployeeDetailsForm(request.POST, files=request.FILES)

        if form.is_valid():

            data = form.cleaned_data
            #print(form.cleaned_data)

            EmployeeDetails.objects.create(**data)

            return redirect('employee-list')

        return render(request, 'myapp/employee_add.html', {'form': form})
    

    
class EmployeeDetailView(View):

    def get(self, request, *args, **kwargs):

        # print(kwargs)

        pk = kwargs.get('pk')

        qs = EmployeeDetails.objects.get(id=pk)

        return render(request, 'myapp/employee_detail.html', {'emp_data': qs})



class EmployeeDeleteView(View):

    def get(self,request, *args, **kwargs):

        id = kwargs.get('pk')

        EmployeeDetails.objects.get(id=id).delete()

        return redirect('employee-list')
    


class EmployeeUpdateView(View):

    def get(self, request, *args, **kwargs):

        id = kwargs.get('pk')

        emp_object = EmployeeDetails.objects.get(id=id)

        form = EmployeeDetailsForm(instance=emp_object)

        return render(request, 'myapp/employee_edit.html', {'form': form})
    
    
    def post(self, request, *args, **kwargs):

        id = kwargs.get('pk')

        emp_object = EmployeeDetails.objects.get(id=id)

        form = EmployeeDetailsForm(request.POST, files=request.FILES, instance=emp_object)

        if form.is_valid():

            form.save()

            return redirect('employee-list')
        
        else:

            return render(request, 'myapp/employee_edit.html', {'form': form})

ems/myapp/templates/myapp/Sample/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body class="bg-red-200">

    <h1 class="fs-1 text-red-600 ">Hello World</h1>
    <div class="animate__animated animate__fadeInLeft"><h3>Example</h3></div>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro laudantium, placeat perferendis asperiores delectus consequatur quam reiciendis voluptatum, minus rem expedita eaque accusamus soluta. Et aut quas consectetur officiis fugiat.
    Harum amet, optio libero consectetur pariatur molestiae veniam totam placeat a repellat inventore et aut debitis ut ipsam officiis unde veritatis facilis. Temporibus animi laboriosam deserunt natus, quia dolore impedit.
    Quis harum maiores voluptas dolore incidunt doloribus non porro repellendus fugit aut molestiae earum, excepturi nemo accusantium totam iure. Sequi praesentium non asperiores animi incidunt ex quas nobis voluptate modi.
    Error exercitationem ad nam ea, saepe laudantium. Excepturi natus eos harum quae deserunt fugit quia vero, asperiores cum nemo, distinctio, aspernatur assumenda animi recusandae numquam. Ipsum amet ipsam earum magni.
    Sed dicta nihil a asperiores suscipit ab illum rerum veritatis earum? Sequi totam cum ipsum nemo magnam, dolore praesentium alias explicabo quaerat quae earum et quidem nulla. Accusamus, consequatur id!
    Quis, ex at. Unde omnis placeat saepe necessitatibus quis amet illo, provident at aliquam. Fugit hic rerum quia iste accusantium nisi eligendi suscipit accusamus, maxime repudiandae cumque, unde totam architecto!
    Libero quae beatae iste, sed possimus dolor ducimus consequatur eveniet id numquam aperiam, laborum corrupti. Molestiae quis saepe exercitationem amet maiores, enim facilis odio eligendi pariatur deserunt quidem asperiores quam.
    Esse soluta explicabo perspiciatis, ducimus sed aspernatur, quo consequatur nihil ipsa corrupti nulla dolores ipsum ea repellat nemo quibusdam alias laborum, cumque dolorum voluptate tempora. Quod labore neque sint ipsa?
    Amet hic sit nam nulla ad architecto itaque, qui, ex exercitationem fugiat ullam suscipit, cupiditate quas asperiores necessitatibus sequi consequuntur est a consectetur doloremque eligendi iure? Reprehenderit corrupti fugiat unde.
    Ea, sequi quasi voluptatem distinctio necessitatibus placeat ratione? Atque, recusandae modi, minima corrupti consequuntur rerum illum, cumque fuga beatae nisi architecto at? Voluptas cum minima quo molestias expedita hic accusamus!</p>
    
    
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos quaerat accusantium dicta natus quam provident quia eligendi necessitatibus? Earum nesciunt voluptas architecto animi consequatur atque qui aspernatur eveniet totam? Quam?
    Rerum dolor deleniti ab cumque, iste excepturi itaque minus commodi non in architecto ducimus. Dolorum rerum similique iusto distinctio in, voluptas unde sit nam. Reprehenderit dolor esse quae! Neque, velit.
    Voluptas reiciendis blanditiis ab quis. Eum et ea modi cupiditate quisquam itaque suscipit obcaecati debitis. Fugit velit fuga assumenda nostrum illo necessitatibus corporis excepturi unde mollitia est odit, quam quo.
    Amet nihil accusantium ex velit ducimus repudiandae culpa perferendis architecto autem! Veniam quam alias velit porro quisquam, laborum aliquid repudiandae est accusantium architecto dicta consequatur expedita. Eaque enim asperiores expedita.
    Unde nulla soluta similique aperiam, error ex! Molestias quisquam cupiditate id quasi veritatis repellendus, adipisci tenetur harum laboriosam minima repellat numquam ea culpa nemo libero quidem suscipit, enim quis! Ad?
    Voluptas sed ab atque tempore saepe similique obcaecati fugiat iusto pariatur aliquam assumenda deserunt modi velit mollitia nulla in qui ipsam, aperiam possimus cum praesentium. Saepe reprehenderit dolorum mollitia neque!
    Quod, neque deserunt odit magni adipisci doloremque cupiditate atque reprehenderit ratione quam architecto hic sit iure repudiandae molestias consectetur nostrum quidem corporis placeat? Vel odit fugit libero dicta ipsam exercitationem.
    Nulla recusandae ipsum quo deleniti qui doloremque repellat voluptatibus obcaecati possimus incidunt, nobis, labore odit architecto ut, asperiores explicabo? Totam error assumenda consectetur, nobis dicta cumque nostrum molestiae doloremque odit?
    Minima possimus, voluptatum magnam provident libero ducimus, nisi mollitia impedit accusamus odit obcaecati similique ipsam error aut maxime perspiciatis dolore laborum fugit delectus. Consectetur voluptatem tempore natus necessitatibus, ipsam in.
    Unde vitae ex officiis est recusandae quia quos ad et debitis pariatur assumenda, nam incidunt voluptas autem cum ut ipsum eius maxime id odio laudantium, nesciunt, necessitatibus enim. Dolore, molestias.</p>
    <div class=""><img class="animate__animated animate__fadeInRight" width="200" src="https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aHVtYW58ZW58MHx8MHx8fDA%3D" alt=""></div>
    

    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto illum iure ullam. Blanditiis, cupiditate saepe incidunt placeat, perspiciatis ad, cum praesentium eos sit numquam asperiores reiciendis hic modi non nam.
    Recusandae delectus natus magnam laudantium magni corporis deserunt accusamus ut minima nemo numquam quae temporibus explicabo earum asperiores, minus unde eaque et quo iusto hic? Sapiente itaque veniam magni dignissimos?
    Cupiditate consectetur asperiores laboriosam. Tempora magni rem quo laboriosam laudantium, sequi alias soluta mollitia doloremque dolorum a eligendi voluptatum debitis doloribus veritatis, assumenda iure fuga unde earum! Eos, vel quas.
    Iusto quisquam consequatur possimus fugit doloribus odit corporis dolor accusantium illo eius placeat inventore at necessitatibus atque, tempora consectetur repudiandae quod cupiditate dolores ab explicabo? Explicabo molestiae ab dignissimos eveniet.
    Architecto voluptas fuga laudantium debitis eaque facilis quod qui labore culpa nostrum quibusdam, quia ut amet corrupti! Magni maiores error pariatur hic? Vero aliquam voluptatem, doloribus iusto reprehenderit delectus fugit.
    Sapiente atque corrupti suscipit at tenetur veritatis perferendis nemo magnam iste nam, facere est unde dolorem quia eaque modi aliquam aperiam minus reprehenderit incidunt nostrum repudiandae esse iusto rerum? Perspiciatis!
    Iure sequi harum quo enim nisi minima nam vitae nihil, porro adipisci numquam sapiente voluptate? Ad, repellendus? Pariatur rem neque vero officiis corrupti magni, nobis obcaecati, ipsum quaerat id aspernatur.
    Dolorem voluptates eaque, totam consequatur iure magnam repellendus aperiam eos unde reiciendis consequuntur voluptas voluptatum facere ipsam, cumque deleniti sapiente nisi suscipit? Blanditiis aliquam ullam, soluta consequuntur quae voluptatem architecto!
    Minus rerum sunt laboriosam ducimus, ut cumque nobis alias maiores facilis officiis! Ex dolor repellat eveniet doloremque nihil ad, saepe cumque eum, iusto blanditiis quos maiores expedita voluptate, porro esse!
    Ipsum consequatur, quis modi ipsa, voluptatem praesentium commodi porro alias perferendis natus ut, a eaque error culpa dolorem eum magnam iure sequi aspernatur labore! Non cupiditate quasi assumenda ut reiciendis!
    Suscipit necessitatibus deleniti consectetur aspernatur quasi debitis explicabo quas fuga deserunt alias natus officia quo dolore culpa, impedit ex nobis ducimus consequuntur tempore incidunt nihil! Quo officia laborum voluptatibus provident.
    Dicta, sunt repellendus? Rem vitae molestias provident ullam aliquid, maxime rerum harum ad iusto eum! Voluptatum ratione labore dicta quaerat error, culpa dolorum neque sequi! Quis illo deserunt nulla quasi.
    Ea voluptas sequi possimus voluptatem quibusdam aperiam debitis facilis incidunt iure nobis repudiandae esse, quis ratione porro adipisci sunt natus neque distinctio dolorem ipsa optio vitae perspiciatis. Repellendus, optio veniam?
    Cumque eos ipsam libero, ducimus saepe laboriosam maiores reprehenderit impedit dicta placeat dolor voluptatibus ipsa suscipit similique. Quod maiores nisi, amet incidunt numquam, eligendi inventore doloribus aut aliquam consequatur modi!
    Voluptate ipsum minus corrupti? Eos ducimus mollitia odit in, minima praesentium, totam architecto quasi iusto autem obcaecati tempore nihil est dolore accusamus nulla libero provident repellat! Laboriosam itaque vero quis.
    Nobis itaque possimus provident nisi? Explicabo tempore porro, voluptas, debitis voluptatum ipsa nesciunt unde repellat expedita quibusdam cumque dolor sit eos beatae commodi, ex quod perspiciatis ab aliquid distinctio nobis.
    Adipisci suscipit neque vel porro in. Et perspiciatis quia doloribus delectus ea distinctio vitae quis, incidunt dicta iste illo ex placeat perferendis, odit facere, rem natus minus corporis blanditiis error.
    Possimus impedit ipsam est ex qui numquam eos, dolorum dolor ipsa earum quasi dicta sequi ratione esse, nemo dolorem obcaecati minus similique officiis ducimus facere, animi molestiae corrupti! Dolore, nam.
    Fugiat repudiandae autem hic, porro possimus veniam dolore ipsam. Neque, asperiores dolore! Molestias dolorem eos voluptatum earum. Totam dolorem at saepe distinctio nobis doloremque vero, atque quia quidem repellendus optio!
    Quasi, perspiciatis! Ipsa qui sed earum recusandae nobis sunt ut, modi labore temporibus delectus porro libero facilis aliquam tempora enim itaque vero, odit dolores, veniam minima ullam iure. Dolorum, illum.
    Aut distinctio blanditiis repellendus quia? Itaque delectus dolorem sed possimus! Maiores odio soluta facere sequi earum nihil fuga aliquid? Recusandae est fugit dolores quasi quibusdam aliquid velit delectus aut! Voluptatibus.
    Odio ab consequuntur nisi aperiam maxime optio vero ducimus, rem praesentium qui accusamus, voluptate delectus possimus beatae, saepe magnam tempore consequatur alias suscipit distinctio. Expedita autem at iusto cumque voluptate.
    Vel voluptatem ducimus aut a exercitationem aliquid impedit qui pariatur nesciunt doloribus dolorem labore quidem ab blanditiis, dignissimos eveniet praesentium? Quod atque, ipsa alias praesentium nostrum esse ullam sequi libero?
    Debitis modi, quam id facere vel earum similique assumenda aliquid voluptatum necessitatibus eaque voluptates quod sit soluta, porro culpa reprehenderit nesciunt quidem blanditiis beatae esse corrupti quia! Corrupti, nam nobis!
    Accusamus eius, voluptates quam eum ducimus pariatur ratione doloribus eligendi ad nesciunt reiciendis praesentium quaerat provident rerum? Autem, veritatis. Quos facilis asperiores qui nemo veritatis commodi vitae eum illo nam.
    Sunt aut ipsa dolorem quod, dolorum totam voluptate laudantium est tempore quisquam facilis omnis ullam, exercitationem odio mollitia unde sed aperiam iste dicta ab voluptatibus iusto natus? Dolorum, vero similique.
    Eum aspernatur voluptatem nulla inventore enim. Ratione, dolor! Atque dignissimos reiciendis ut perspiciatis nihil facere hic? Repellendus ad quas consequuntur dolor? Corrupti repudiandae eligendi nulla totam nam cumque ullam quisquam.
    Unde, veniam eveniet porro, nesciunt molestias, amet ipsa soluta neque eos esse obcaecati dolore molestiae quo asperiores vel suscipit earum magnam quae rem iure! Natus ad distinctio ipsam neque ullam!
    Maxime veritatis dolorum ipsa saepe quae in sunt praesentium sint reiciendis, accusantium aperiam, laboriosam adipisci. Aliquid minima autem velit, iusto a porro adipisci officiis reprehenderit reiciendis, consectetur magnam alias aspernatur?
    Aperiam blanditiis architecto sed placeat tempore esse repudiandae nihil fugit, ipsa debitis expedita provident odio cumque excepturi libero rerum animi laboriosam sequi quas beatae iure doloremque cupiditate suscipit! Quos, ullam.</p>



    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

ems/myapp/templates/myapp/Sample/index.html
{% extends "myapp/base.html" %}

{% load compress %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block main-content %}
<body class="">
    
    <h1 class="text-green-600 text-3xl">This is Index.html</h1>
    <p class="text-purple-700 mx-auto">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Adipisci ullam saepe, reiciendis tempore in nostrum totam! Vero ea neque, possimus impedit saepe nesciunt placeat voluptatum quia quam eaque consequuntur accusantium!</p>

</body>

{% endblock main-content %} 

ems/myapp/templates/myapp/employee_add.html
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Employee</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    
    <link rel="stylesheet" href="../../../static/css/my-styles.css">
</head>


<body class="emp-add bg-body-tertiary">

    <h2 class="text-center mb-3 py-2 text-primary-emphasis bg-body-secondary sticky-top">Add Employee</h2>

    <div class="container">
        <div class="row">
            <div class="col-md-2 col-lg-3"></div>
            <div class="col-md-8 col-lg-6 p-2">

                <form method="post" enctype="multipart/form-data" class="p-3 shadow border border-3 rounded my-3">

                    {%csrf_token%}
    
                    {{form}}
    
                    <div class="text-center">
                        <button type="submit" class="btn btn-info text-light px-5 my-3">Add</button>
                        <a href="{% url 'employee-list' %}" class="btn btn-secondary">Cancel</a>
                    </div>
                    
                </form>

                
            </div>
            <div class="col-md-2 col-lg-3"></div>
        </div>
    </div>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>


    <!-- <script>
        document.querySelector('.form-select').setAttribute('disabled', 'true');
    </script> -->

    <script>
        document.querySelector('div:has(#id_dob)> label').innerHTML = 'Date of birth:';

        
    </script>
</body>

</html>

ems/myapp/templates/myapp/employee_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Employee</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <link rel="stylesheet" href="../../../static/css/my-styles.css">

</head>

<body class="emp-update bg-body-tertiary">
    
    <h2 class="text-center mb-3 p-2 text-primary-emphasis bg-body-secondary sticky-top">Edit Employee</h2>

    <div class="container">
        <div class="row">
            <div class="col-md-2 col-lg-3"></div>
            <div class="col-md-8 col-lg-6 p-2">

                <form method="post" enctype="multipart/form-data" class=" p-3 shadow border border-3 rounded my-3">

                    {%csrf_token%}
                    
                    
                    {{form}}
    
                    <div class="text-center">
                        <button type="submit" class="btn btn-info text-white fw-medium my-3 ">Save Changes</button>
                        <a href="{% url 'employee-list' %}" class="btn btn-secondary">Cancel</a>
                    </div>
                    
                </form>

                {% comment %} <form action="" class="p-3">
                    <div class="mb-3">
                        <label for="">Employee ID / Code</label>
                        <input class="form-control" type="text" name="emp_id" placeholder="Enter emp ID">
                    </div>
                    <div class="mb-3">
                        <label for="">First Name</label>
                        <input class="form-control" type="text" name="first_name" placeholder="Enter first name">
                    </div>
                    <div class="mb-3">
                        <label for="">Last Name</label>
                        <input class="form-control" type="text" name="last_name" placeholder="Enter last name">
                    </div>
                    <div class="mb-3">
                        <label for="">Image</label>
                        <input class="form-control" type="file" accept="image/*" name="image" id="">
                    </div>
                    <div class="mb-3">
                        <label for="">Phone</label>
                        <input class="form-control" type="text" name="phone" placeholder="Enter phone">
                    </div>
                    <div class="mb-3">
                        <label for="">Email</label>
                        <input class="form-control" type="email" name="email" placeholder="Enter email">   
                    </div>
                    <div class="mb-4">
                        <label for="">Gender</label>
                        <div class="my-2 row gx-2">
                            <div class="col-sm-12 col-md ">
                                <input class="form-check-input mx-3" type="radio" name="gender" value="male" id="" checked> Male    
                            </div>
                            <div class="col-sm-12 col-md ">
                                <input class="form-check-input mx-3" type="radio" name="gender" value="female" id=""> Female     
                            </div>
                            <div class="col-sm-12 col-md ">
                                <input class="form-check-input mx-3" type="radio" name="gender" value="other" id=""> Other     
                            </div>
                            
                        </div>        
                    </div>
                    <div class="mb-3">
                        <label for="">Date of birth</label>
                        <input class="form-control" type="date">
                    </div>
                    <div class="mb-3">
                        <label for="">Address</label>
                        <textarea class="form-control" type="text" name="address" placeholder="Enter address"></textarea>      
                    </div>
                    <div class="mb-3">
                        <label for="">Date Hired</label>
                        <input class="form-control" type="date" name="date_hired" id="">
                    </div>
                    <div class="mb-3">
                        <label for="">Status</label>
                        <select class="form-select" name="status" id="" disabled>
                            <option>--Select--</option>
                            <option value="1" selected>Active</option>
                            <option value="0">Inactive</option>
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="">Department</label>
                        <input class="form-control" type="text" name="department" id="">
                    </div>
                    <div class="mb-3">
                        <label for="">Position</label>
                        <input class="form-control" type="text" name="position" id="">
                    </div>
                    <div class="mb-3">
                        <label for="">Salary</label>
                        <input class="form-control" type="number" name="salary" id="">
                    </div>
                    <div class="mb-3">
                        <input class=" mt-3 text-white btn btn-info fw-bold fs-4 form-control" type="submit" value="Add Employee">
                    </div>
                </form> {% endcomment %}

                
            </div>
            <div class="col-md-2 col-lg-3"></div>
        </div>
    </div>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>

        
    <script>
        document.querySelector('label[for="id_dob"]').innerHTML = 'Date of birth:'
    </script>

</body>
</html>